# Generated by Django 2.0.2 on 2018-02-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gab', '0002_auto_20180221_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='boxes/')),
                ('quantity', models.CharField(blank=True, max_length=250)),
                ('quality', models.CharField(blank=True, max_length=250)),
                ('feeds', models.CharField(blank=True, max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('shipping', models.CharField(blank=True, max_length=250)),
                ('category', models.ManyToManyField(to='gab.Category')),
            ],
        ),
    ]
