# Generated by Django 2.0.2 on 2018-02-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gab', '0004_auto_20180221_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
