# Generated by Django 2.0.2 on 2018-02-21 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gab', '0005_auto_20180221_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products')),
                ('description', models.TextField()),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gab.Box')),
            ],
        ),
    ]
